name: Publish to JSR
on:
  push:
    tags:
      - '*'
permissions:
  contents: read
  id-token: write
jobs:
  jsr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check tag version
        id: check
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          MAJOR=$(echo $TAG | cut -d. -f1)
          if [[ "$MAJOR" =~ ^[0-9]+$ && "$MAJOR" -gt 3 ]]; then
            echo "version_ok=true" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Publish to JSR
        if: steps.check.outputs.version_ok == 'true'
        run: npx jsr publish
